CREATE TEMPORARY TABLE tmp_mitsubishi_seed (
  category_slug VARCHAR(100) NOT NULL,
  sku VARCHAR(100) NOT NULL,
  product_type VARCHAR(120) NOT NULL,
  series_name VARCHAR(120) NOT NULL,
  PRIMARY KEY (sku)
);

INSERT INTO tmp_mitsubishi_seed (category_slug, sku, product_type, series_name) VALUES
('a-series','A1SJ71UC24-R2','Serial Communication Module','A Series'),
('a-series','A1SJ71UC24-R4','Serial Communication Module','A Series'),
('a-series','A1SJ71QE71N-B5','Ethernet Interface Module','A Series'),
('a-series','A1SX41','Input Module','A Series'),
('a-series','A1SX42','Input Module','A Series'),
('a-series','A1SY50','Output Module','A Series'),
('a-series','A1S68DAV','Analog Output Module','A Series'),
('a-series','A1S68DAI','Analog Output Module','A Series'),
('a-series','A1S62RD3','Temperature Input Module','A Series'),
('a-series','A1S62RD4','Temperature Input Module','A Series'),

('freqrol-fr','FR-A740-0.4K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-A740-1.5K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-A740-2.2K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-A740-3.7K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-D740-0.4K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-D740-1.5K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-E740-0.4K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-E740-1.5K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-F740-2.2K','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-A840-00023-2-60','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-E840-0016-2-60','Inverter / VFD','FREQROL FR'),
('freqrol-fr','FR-F840-00126-2-60','Inverter / VFD','FREQROL FR'),

('fx-series','FX3U-16MR/ES','PLC CPU Module','FX Series'),
('fx-series','FX3U-32MR/ES','PLC CPU Module','FX Series'),
('fx-series','FX3U-48MR/ES','PLC CPU Module','FX Series'),
('fx-series','FX3U-64MR/ES','PLC CPU Module','FX Series'),
('fx-series','FX3U-16MT/ES','PLC CPU Module','FX Series'),
('fx-series','FX5U-32MR/ES','PLC CPU Module','FX Series'),
('fx-series','FX5U-32MT/ES','PLC CPU Module','FX Series'),
('fx-series','FX5U-64MR/ES','PLC CPU Module','FX Series'),
('fx-series','FX5UC-32MT/DSS','PLC CPU Module','FX Series'),
('fx-series','FX3G-40MR/ES-A','PLC CPU Module','FX Series'),
('fx-series','FX2N-32MR-ES/UL','PLC CPU Module','FX Series'),
('fx-series','FX3U-4AD','Analog Input Module','FX Series'),

('got1000','GT1020-LBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1030-LBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1030-HBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1150-QLBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1155-QSBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1555-QSBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1565-VTBD','HMI Operator Terminal','GOT1000'),
('got1000','GT1575-VTBA','HMI Operator Terminal','GOT1000'),
('got1000','GT1585-STBA','HMI Operator Terminal','GOT1000'),
('got1000','GT1665M-STBA','HMI Operator Terminal','GOT1000'),
('got1000','GT1675M-STBA','HMI Operator Terminal','GOT1000'),
('got1000','GT1695M-XTBA','HMI Operator Terminal','GOT1000'),

('hf-series','HF-KP13','Servo Motor','HF Series'),
('hf-series','HF-KP23','Servo Motor','HF Series'),
('hf-series','HF-KP43','Servo Motor','HF Series'),
('hf-series','HF-KP73','Servo Motor','HF Series'),
('hf-series','HF-MP13','Servo Motor','HF Series'),
('hf-series','HF-MP23','Servo Motor','HF Series'),
('hf-series','HF-MP43','Servo Motor','HF Series'),
('hf-series','HF-SP52','Servo Motor','HF Series'),
('hf-series','HF-SP102','Servo Motor','HF Series'),
('hf-series','HF-SP152','Servo Motor','HF Series'),
('hf-series','HF-SP202','Servo Motor','HF Series'),
('hf-series','HF-JP1534','Servo Motor','HF Series'),

('hg-series','HG-KR13','Servo Motor','HG Series'),
('hg-series','HG-KR23','Servo Motor','HG Series'),
('hg-series','HG-KR43','Servo Motor','HG Series'),
('hg-series','HG-KR73','Servo Motor','HG Series'),
('hg-series','HG-MR13','Servo Motor','HG Series'),
('hg-series','HG-MR23','Servo Motor','HG Series'),
('hg-series','HG-MR43','Servo Motor','HG Series'),
('hg-series','HG-SR52','Servo Motor','HG Series'),
('hg-series','HG-SR102','Servo Motor','HG Series'),
('hg-series','HG-SR152','Servo Motor','HG Series'),
('hg-series','HG-JR103','Servo Motor','HG Series'),
('hg-series','HG-SR1524B','Servo Motor','HG Series'),

('mds-servo-drives','MDS-D-SVJ3-04NA','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-D-SVJ3-10NA','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-D-SVJ3-20NA','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-DH-CV-185','CNC Converter Unit','MDS Servo Drives'),
('mds-servo-drives','MDS-DH-SP-37','CNC Spindle Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-DM-SPV3-20080','CNC Spindle Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-B-SVJ2-10','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-B-SVJ2-20','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-C1-V1-20','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-C1-V2-3520','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-D2-V1-20','CNC Servo Drive','MDS Servo Drives'),
('mds-servo-drives','MDS-D2-SP-110','CNC Spindle Drive','MDS Servo Drives'),

('melsec-q','Q00JCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q00CPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q01CPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q02CPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q03UDCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q04UDHCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q06UDHCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q13UDHCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q26UDHCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','Q03UDVCPU','PLC CPU Module','Melsec-Q'),
('melsec-q','QJ71E71-100','Ethernet Interface Module','Melsec-Q'),
('melsec-q','QX40','Input Module','Melsec-Q'),

('melservo-hc','HC-KFS13','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-KFS23','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-KFS43','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-KFS73','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-MFS13','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-MFS23','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-MFS43','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-SFS52','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-SFS102','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-RFS103','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-UFS72','Servo Motor','MELSERVO HC'),
('melservo-hc','HC-LFS102','Servo Motor','MELSERVO HC'),

('melservo-mr-j2','MR-J2-10A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2-20A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2-40A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2-60A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2-70A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2-100A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2S-10A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2S-20A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2S-40A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2S-70A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2S-100A','Servo Amplifier','MELSERVO MR-J2'),
('melservo-mr-j2','MR-J2S-200A','Servo Amplifier','MELSERVO MR-J2'),

('melservo-mr-j3','MR-J3-10A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-20A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-40A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-70A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-100A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-200A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-350A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-500A','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-10B','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-40B','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-100B','Servo Amplifier','MELSERVO MR-J3'),
('melservo-mr-j3','MR-J3-200B','Servo Amplifier','MELSERVO MR-J3'),

('melservo-mr-j4','MR-J4-10A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-20A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-40A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-70A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-100A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-200A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-350A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-500A','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-10B','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4-40B','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4W2-22B','Servo Amplifier','MELSERVO MR-J4'),
('melservo-mr-j4','MR-J4W3-222B','Servo Amplifier','MELSERVO MR-J4');

UPDATE products p
JOIN tmp_mitsubishi_seed s ON s.sku = p.sku
JOIN categories c ON c.slug = s.category_slug
SET
  p.name = CONCAT('Mitsubishi ', s.sku, ' ', s.product_type),
  p.short_description = CONCAT('Mitsubishi ', s.sku, ' ', s.product_type, ' for industrial automation maintenance, repair, and replacement. 12-month warranty and worldwide shipping available.'),
  p.description = CONCAT(
    'Mitsubishi ', s.sku, ' ', s.product_type, '\n\n',
    'Mitsubishi ', s.sku, ' belongs to the ', s.series_name, ' product range and is used for industrial automation maintenance, repair, retrofit, and spare parts replacement. ',
    'Confirm the exact model, voltage, interface, capacity, and machine configuration before ordering.\n\n',
    'Key details\n',
    '- Brand: Mitsubishi Electric\n',
    '- Model: ', s.sku, '\n',
    '- Series: ', s.series_name, '\n',
    '- Type: ', s.product_type, '\n',
    '- Condition: New / Refurbished / Used (please confirm before ordering)\n',
    '- Warranty: 12 months\n',
    '- Lead time: 3-7 days\n',
    '- Shipping: Worldwide'
  ),
  p.brand = 'Mitsubishi',
  p.model = s.sku,
  p.part_number = s.sku,
  p.category_id = c.id,
  p.manufacturer = 'Mitsubishi Electric',
  p.meta_title = CONCAT('Mitsubishi ', s.sku, ' ', s.product_type, ' | Vcocnc'),
  p.meta_description = CONCAT('Mitsubishi ', s.sku, ' ', s.series_name, ' ', s.product_type, ' for automation repair and replacement. Compatibility support, 12-month warranty, and worldwide shipping.'),
  p.meta_keywords = CONCAT(s.sku, ', Mitsubishi ', s.series_name, ', ', s.product_type, ', Mitsubishi Electric parts, industrial automation parts, Vcocnc'),
  p.compatibility_info = CONCAT('Confirm compatibility for ', s.sku, ' against the original model label, controller or drive series, voltage, capacity, interface, firmware, and machine configuration before ordering.'),
  p.installation_guide = CONCAT('Install ', s.sku, ' only after isolating power and following the Mitsubishi Electric manual and machine builder maintenance procedure.'),
  p.maintenance_tips = CONCAT('Keep ', s.sku, ' clean, dry, and properly stored. Check terminals, connectors, cooling, and cabinet conditions during maintenance.'),
  p.updated_at = NOW(3);

INSERT INTO products (
  sku, name, slug, short_description, description, price, stock_quantity, min_stock_level,
  brand, model, part_number, category_id, is_active, is_featured,
  meta_title, meta_description, meta_keywords, disable_auto_seo, image_urls,
  warranty_period, condition_type, origin_country, manufacturer, lead_time, minimum_order_quantity,
  packaging_info, certifications, technical_specs, compatibility_info, installation_guide, maintenance_tips,
  created_at, updated_at
)
SELECT
  s.sku,
  CONCAT('Mitsubishi ', s.sku, ' ', s.product_type),
  CONCAT('mitsubishi-', TRIM(BOTH '-' FROM LOWER(REGEXP_REPLACE(s.sku, '[^A-Za-z0-9]+', '-')))),
  CONCAT('Mitsubishi ', s.sku, ' ', s.product_type, ' for industrial automation maintenance, repair, and replacement. 12-month warranty and worldwide shipping available.'),
  CONCAT(
    'Mitsubishi ', s.sku, ' ', s.product_type, '\n\n',
    'Mitsubishi ', s.sku, ' belongs to the ', s.series_name, ' product range and is used for industrial automation maintenance, repair, retrofit, and spare parts replacement. ',
    'Confirm the exact model, voltage, interface, capacity, and machine configuration before ordering.\n\n',
    'Key details\n',
    '- Brand: Mitsubishi Electric\n',
    '- Model: ', s.sku, '\n',
    '- Series: ', s.series_name, '\n',
    '- Type: ', s.product_type, '\n',
    '- Condition: New / Refurbished / Used (please confirm before ordering)\n',
    '- Warranty: 12 months\n',
    '- Lead time: 3-7 days\n',
    '- Shipping: Worldwide'
  ),
  0.00,
  1,
  0,
  'Mitsubishi',
  s.sku,
  s.sku,
  c.id,
  1,
  0,
  CONCAT('Mitsubishi ', s.sku, ' ', s.product_type, ' | Vcocnc'),
  CONCAT('Mitsubishi ', s.sku, ' ', s.series_name, ' ', s.product_type, ' for automation repair and replacement. Compatibility support, 12-month warranty, and worldwide shipping.'),
  CONCAT(s.sku, ', Mitsubishi ', s.series_name, ', ', s.product_type, ', Mitsubishi Electric parts, industrial automation parts, Vcocnc'),
  0,
  JSON_ARRAY(),
  '12 months',
  'new',
  'Japan',
  'Mitsubishi Electric',
  '3-7 days',
  1,
  CONCAT('Standard export packaging for Mitsubishi ', s.sku, '.'),
  'CE / RoHS where applicable; confirm by exact model before ordering.',
  JSON_OBJECT('brand','Mitsubishi Electric','series',s.series_name,'model',s.sku,'type',s.product_type),
  CONCAT('Confirm compatibility for ', s.sku, ' against the original model label, controller or drive series, voltage, capacity, interface, firmware, and machine configuration before ordering.'),
  CONCAT('Install ', s.sku, ' only after isolating power and following the Mitsubishi Electric manual and machine builder maintenance procedure.'),
  CONCAT('Keep ', s.sku, ' clean, dry, and properly stored. Check terminals, connectors, cooling, and cabinet conditions during maintenance.'),
  NOW(3),
  NOW(3)
FROM tmp_mitsubishi_seed s
JOIN categories c ON c.slug = s.category_slug
LEFT JOIN products existing_sku ON existing_sku.sku = s.sku
LEFT JOIN products existing_slug ON existing_slug.slug = CONCAT('mitsubishi-', TRIM(BOTH '-' FROM LOWER(REGEXP_REPLACE(s.sku, '[^A-Za-z0-9]+', '-'))))
WHERE existing_sku.id IS NULL
  AND existing_slug.id IS NULL;

SELECT c.slug, c.name, COUNT(p.id) AS products
FROM categories c
LEFT JOIN products p ON p.category_id = c.id
WHERE c.slug IN (
  'a-series','freqrol-fr','fx-series','got1000','hf-series','hg-series',
  'mds-servo-drives','melsec-q','melservo-hc','melservo-mr-j2','melservo-mr-j3','melservo-mr-j4'
)
GROUP BY c.id
ORDER BY c.sort_order, c.id;
