'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { MagnifyingGlassIcon, ArrowRightIcon, ChevronDownIcon, CubeIcon } from '@heroicons/react/24/outline';

type Category = { id: number; name: string; slug: string; path?: string; description?: string; image_url?: string; product_count?: number; children?: Category[] };
function flatten(nodes: Category[], parentPath = ''): Category[] { return nodes.flatMap((node) => { const path = node.path || (parentPath ? `${parentPath}/${node.slug}` : node.slug); return [{ ...node, path }, ...flatten(node.children || [], path)]; }); }
function totalCount(category: Category): number { return Number(category.product_count || 0) + (category.children || []).reduce((sum, child) => sum + totalCount(child), 0); }

export default function CategoriesDirectory({ categories }: { categories: Category[] }) {
  const [query, setQuery] = useState('');
  const [showAll, setShowAll] = useState(false);
  const flat = useMemo(() => flatten(categories), [categories]);
  const visible = query.trim() ? flat.filter((category) => `${category.name} ${category.description || ''}`.toLowerCase().includes(query.trim().toLowerCase())) : (showAll ? flat : categories);
  const totalProducts = categories.reduce((sum, category) => sum + totalCount(category), 0);
  return <main className="min-h-screen bg-slate-50">
    <section className="relative overflow-hidden bg-[#081b33] px-4 py-16 text-white sm:px-6 lg:px-8 lg:py-24"><div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-yellow-400/20 blur-3xl" /><div className="relative mx-auto max-w-7xl"><p className="mb-4 text-sm font-bold uppercase tracking-[0.24em] text-yellow-300">FANUC &amp; automation parts</p><h1 className="max-w-3xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Browse product categories</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-200">Find servo drives, motors, control boards, I/O modules and other industrial automation parts by category.</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-semibold"><span className="rounded-full bg-yellow-400 px-4 py-2 text-slate-950">{flat.length} categories</span><span className="rounded-full border border-white/20 px-4 py-2 text-white">{totalProducts.toLocaleString()} active products</span></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black text-slate-950">Shop by category</h2><p className="mt-1 text-sm text-slate-600">Select a category to view matching products.</p></div><div className="relative w-full sm:w-80"><MagnifyingGlassIcon className="pointer-events-none absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search categories" className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none ring-yellow-300 transition focus:border-yellow-500 focus:ring-2" /></div></div>
      {visible.length === 0 ? <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">No matching categories found.</div> : <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((category) => { const path = category.path || category.slug; const count = totalCount(category); return <Link key={`${category.id}-${path}`} href={`/categories/${path}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:border-yellow-400 hover:shadow-xl"><div className="relative flex h-44 items-center justify-center overflow-hidden bg-gradient-to-br from-yellow-50 via-white to-slate-100">{category.image_url ? <Image src={category.image_url} alt={category.name} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" /> : <CubeIcon className="h-16 w-16 text-yellow-500 transition group-hover:scale-110" />}<span className="absolute right-3 top-3 rounded-full bg-yellow-400 px-3 py-1 text-xs font-bold text-slate-950">{count} products</span></div><div className="p-5"><h3 className="text-lg font-bold text-slate-950 group-hover:text-yellow-700">{category.name}</h3><p className="mt-2 min-h-12 line-clamp-2 text-sm leading-6 text-slate-600">{category.description || 'Browse compatible industrial automation parts in this category.'}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-yellow-700">View products <ArrowRightIcon className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>; })}</div>}
      {!query.trim() && categories.length !== flat.length && <button type="button" onClick={() => setShowAll((value) => !value)} className="mx-auto mt-8 flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-bold text-slate-800 transition hover:border-yellow-500 hover:text-yellow-700">{showAll ? 'Show top-level categories' : 'Show all subcategories'} <ChevronDownIcon className={`h-4 w-4 transition ${showAll ? 'rotate-180' : ''}`} /></button>}
    </section>
  </main>;
}
